### ISSUE TITLE
how to save the oauth token for later use

### ISSUE THREAD

**Issue by vickyagrl** [3pillarlabs/socialauth#49]
how we can save the tokens for authenticated user in pur database to use it at later stage? please assist.

**Comment by vickyagrl** [comment]
can anyone provide me the answer for my query please?

**Comment by stefanbaritchii** [comment]
Hi vickyagrl,

Can you please be more specific please?

Are you interested in saving a tocken into a database?

**Comment by vickyagrl** [comment]
yes. I want to save the tokens in my database so that i can use it at any later point of time to send the posts to the user profiles.

**Comment by stefanbaritchii** [comment]
Hello,

Unfortunately saving to database is out of the scope of this API(due to various reasons - client's own database schema, client's own DB server, etc) and due to the same reasons we don't plan it to be supported in future. However you may find some useful tutorials about saving to database (depending on technology), based on the most used java APIs here:

https://docs.oracle.com/javase/tutorial/jdbc/basics/ (if you're going to vanilla jdbc as persistance layer)
http://www.tutorialspoint.com/hibernate/hibernate_tutorial.pdf  (if you're planning to use hibernate as ORM)
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html (if you're planning to use spring)

**Comment by 3pillarlabs** [comment]
@vickyagri - please try
https://github.com/3pillarlabs/socialauth/tree/master/socialauth-cmd-utility

As Stefan has already mentioned that there is no direct way, however you
can use this utility to generate a long lived token for providers that
support this functionality.

**Comment by tarun-nagpal** [comment]
You can save the serialized AccessGrant object or only accesstoken where you what to persist.
To get AccessGrant object use 
AccessGrant accessGrant = provider.getAccessGrant();
Save this object or 
String token = provider.getAccessGrant().getKey();

Later you can use this to get provider object.
If you are saving AccessGrant object then you can use
socialAuthManager.setSocialAuthConfig(socialAuthConfig)
socialAuthManager.connect(accessGrant) method can be used to get AuthProvider object. 

If you are saving token only then you can use
AccessGrant accessGrant = new AccessGrant();
accessGrant.setKey(token); //pass saved token
accessGrant.setProviderId(providerId); //pass provider id for which this token in generated like facebook, linkedin

AuthProvider provider = socialAuthManager.connect(accessGrant);

**Comment by tarun-nagpal** [comment]
I hope above response helped you to sort out persistence issue.

**Comment by vickyagrl** [comment]
Thanks a lot Tarun. I am to store the tokens and can use it perfectly for later use.
