### ISSUE TITLE
read_stream is not a valid Facebook permission anymore

### ISSUE THREAD

**Issue by AveryRegier** [3pillarlabs/socialauth#60]
The following message is shown to developers when the 'read_stream' permission is used:

Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

read_stream needs removed at this line:

https://github.com/3pillarlabs/socialauth/blob/master/socialauth/src/main/java/org/brickred/socialauth/provider/FacebookImpl.java#L86

**Comment by isaquexavier** [comment]
Hi Everyone,

I am facing the same problem, someone has any update about the bug fix?

@AveryRegier do you have any workaround for this bug?

Thank you guys!

**Comment by AveryRegier** [comment]
I ended up setting Facebook to AUTHENTICATE_ONLY.

                SocialAuthConfig conf = SocialAuthConfig.getDefault();
                Properties properties = new Properties();
                properties.load(new StringReader(propString));
                conf.setApplicationProperties(properties);
                manager = new SocialAuthManager();
                manager.setSocialAuthConfig(conf);
                manager.setPermission("facebook", Permission.AUTHENTICATE_ONLY);

**Comment by isaquexavier** [comment]
Hi Guys,

About this problem, there is a fork from jolivares which fixes it and also another problem related to email fetching. Could you guys from 3pillarlabs check this implementation and validate in order to release a fixed version, I have tested and worked fine to me.

> Fixed Class (FacebookImpl)
https://github.com/jolivares/socialauth/commit/ffb2be3000c9ca0ad2a66f15fce4dc15b6aab722
https://github.com/3pillarlabs/socialauth/network

@AveryRegier  In my case I need some properties/fields from the user's profile so I can't simply use the Permission.AUTHENTICATE_ONLY.

Thanks a lot !

**Comment by sayantam** [comment]
The Facebook implementation uses FB API 2.2 and the demo using read_stream is working as expected. The implementation needs to be upgraded to 2.4 FB API, which will be a separate ticket.
